### ISSUE TITLE
UnityChanがバク転すると床を貫通する問題

### ISSUE THREAD

**Issue by fummicc1** [fummicc1/Dev012Animation#2]
# UnityChanがバク転すると床を貫通する問題
## 問題点
 - Unity Chanがバク転をすると元のY座標よりも少し小さくなって床を貫通してしまう。
<img width="660" alt="2018-09-13 9 23 30" src="https://user-images.githubusercontent.com/28649401/45460209-0e8ce880-b737-11e8-8ba1-2df8f5ba432f.png">

**Comment by m1ya** [comment]
ここに関してはアニメーション自体の問題なのでどうしようもないところが強いんだよね……
バク転のタイミングで座標を少しあげるスクリプトを書いてあげるとか、
根本的な解決方法はないかな

**Comment by m1ya** [comment]
参考！
http://tsubakit1.hateblo.jp/entry/2017/01/30/233000

**Comment by fummicc1** [comment]
@m1ya  貫通はしなくなりました！ありがとうございます！
