### ISSUE TITLE
Character達が無限に移動できる問題

### ISSUE THREAD

**Issue by fummicc1** [fummicc1/Dev012Animation#3]
# Character達が無限に移動できる問題
## 環境
 - 教科書13の「アニメーション」です。
## 問題点
 - 作った平面の上にアバターを置いたのですが、その平面を超えてもアバターがまっすぐ進み、空を走っている状態になってしまった。Rigidbodyがないからだと思い、Rigidbodyをアバターにつけてみたら、下に落ちていった。（床がある状態でも貫通して）
<img width="660" alt="2018-09-13 9 23 44" src="https://user-images.githubusercontent.com/28649401/45460782-9d4f3480-b73a-11e8-947f-151b4d5851da.png">

**Comment by m1ya** [comment]
当たり判定(Collider)がプレイヤーについていないと落ちてしまう！
ついているかしら？

**Comment by m1ya** [comment]
どんな状態だろう？
転げてる状態で走り回っちゃう感じかな？
結構起きるというか、うまく設定してあげないといけないんだよね……

**Comment by fummicc1** [comment]
@m1ya Messengerに現状の動画を送りました！Rigidbodyのvelocityを変更するのは試したんですけど効果なくてアドバイス欲しいです…

**Comment by m1ya** [comment]
<img width="243" alt="2018-09-13 23 29 50" src="https://user-images.githubusercontent.com/19634955/45494886-0079af00-b7ad-11e8-8a90-434f2583251d.png">

Unityの中での座標系は一般的に現実世界との対応として、yが上下、xが左右、zが前後なんだよね！
このプロジェクトだと、これみてこれ見てもらうとわかるかもしれないのだけど、現実世界でいうと壁に足くっつけてる状態になってて、何もいじらないと重力はyの負の方向に働くので、キャラクターの後ろにひらひら落ちていった（ひらひらするのはMass、質量の問題で軽すぎるから！）わけだね！
